apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260617-135113-9euz8ono1vsf-service
spec:
  selector:
    app: enterprise-system-20260617-135113-9euz8ono1vsf
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
